CREATE TABLE tbUser (
		userId INT NOT NULL,
		name VARCHAR(255) NOT NULL UNIQUE,
		email VARCHAR(255) NOT NULL UNIQUE,
		password VARCHAR(255) NOT NULL,
		CONSTRAINT userId_PK PRIMARY KEY (userId)
);